name: Build and push Docker image upon Push And Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  composer_update:
    name: Update Composer dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Composer dependencies
        run: |
          cd app
          composer update

  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [composer_update]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: app
          file: app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aws-bucket:latest

  
  Deploy_images:
    name: Setup SSH and deploy images
    needs: [composer_update]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker compose with Load Balancer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/nico/aws-s3-memebank
            sudo docker-compose up -d
